#
#
# This build script is provided by: https://github.com/svparijs/TravisCi.Example
# Author: Sebastiaan van Parijs
#
# For any issues of feedback report it at Github
#
# The TYPO3 project - inspiring people to share!
#

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.3

# optionally specify a list of environments, for example to test different RDBMS
env:


# Setting up pre-requirements
before_script:
  - cd ..
  - rm -rf payjunction-php
  - git clone git://github.com/andrewjwolf/payjunction-php.git
  - cd payjunction-php
  - composer install --dev --verbose
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - pwd
script:

notifications:
